# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testseal
      - MYSQL_DATABASE=seal_linking
      - MYSQL_USER=seal_linking
      - MYSQL_PASSWORD=123clauer
  web-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
networks:
  spring-boot-mysql-network:
    driver: bridge


#version: '3.3'
#services:
#  db:
#    image: mysql:5.7
#    container_name: mysql-standalone
#    restart: always
#    environment:
#      MYSQL_DATABASE: 'seal_linking'
#      MYSQL_USER: 'seal_linking'
#      # You can use whatever password you like
#      MYSQL_PASSWORD: '123clauer'
#      # Password for root access
#      MYSQL_ROOT_PASSWORD: 'sealtest'
#    ports:
#      # <Port exposed> : < MySQL Port running inside container>
#      - '4000:3306'
#    expose:
#      # Opens port 3306 on the container
#      - '3306'
#      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql
## Names our volume
#volumes:
#  my-db: