# spring-boot-docker/docker-compose.yml
version: "3.7"
services:
  mysql-service:
    image: mysql:5.7
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=testseal
      - MYSQL_DATABASE=seal_linking
      - MYSQL_USER=seal_linking
      - MYSQL_PASSWORD=123clauer
  web-service:
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    image: msirvent/linking_web-service:v1.1
    ports:
      - "8070:8090"
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service
    volumes:
      - /etc/seal:/app/data
networks:
  spring-boot-mysql-network:
    driver: bridge