spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seal_linking?autoReconnect=true
    username: seal_linking
    password: 123clauer
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: create
    show-sql: true

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true