spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seal_linking?autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: seal_linking
    password: 123clauer
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: create
    show-sql: true
server:
  port: 8090
linking:
  cm:
    getAttributeProfilesPath: /cm/metadata/attributes/
    getAttributeSetByProfilePath: /cm/metadata/attributes/, attrProfileId
    getExternalEntitiesPath: /cm/metadata/externalEntities/
    getEntityMetadataSetPath: /cm/metadata/externalEntities/, collectionId
    getEntityMetadataPath: /cm/metadata/externalEntities/, collectionId, entityId
    getAllMicroservicesPath: /cm/metadata/microservices/
    getMicroservicesByApiClassPath: /cm/metadata/microservices/, apiClass
    getInternalsPath: /cm/metadata/internal/
    getConfigurationPath: /cm/metadata/internal/, confId
    cache:
      lifetime: 3600
    url: https://vm.project-seal.eu:9083
  sm:
    url: http://5.79.83.118:9090
  keystore:
    path: /etc/seal/testKeys/keystore.jks
    pass: keystorepass
    key.pass: selfsignedpass
    httpsig.cert.alias: 1
    httpsig.attempts:
    async.signature: true
    signing.secret: QjG+wP1CbAH2z4PWlWIDkxP4oRlgK2vos5/jXFfeBw8=
  request:
    expire: 86400
    lloa: low
    # Validity of an issued link. 0 means permanent
    validityDays: 5

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true


##
## SEAL configuration manager. To be read from environment variables (dockerization)
##
linking:
  cm:
    getAttributeProfilesPath: /cm/metadata/attributes/
    getAttributeSetByProfilePath: /cm/metadata/attributes/, attrProfileId
    getExternalEntitiesPath: /cm/metadata/externalEntities/
    getEntityMetadataSetPath: /cm/metadata/externalEntities/, collectionId
    getEntityMetadataPath: /cm/metadata/externalEntities/, collectionId, entityId
    getAllMicroservicesPath: /cm/metadata/microservices/
    getMicroservicesByApiClassPath: /cm/metadata/microservices/, apiClass
    getInternalsPath: /cm/metadata/internal/
    getConfigurationPath: /cm/metadata/internal/, confId
    cache:
      lifetime: 3600
    url: https://vm.project-seal.eu:9083

  request:
    expire: 86400
    lloa: low
    # Validity of an issued link. 0 means permanent
    validityDays: 0
