spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seal_linking?autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username:
    password:
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: create
    show-sql: true
server:
  port: 8090
linking:
  cm:
    getAttributeProfilesPath: /cm/metadata/attributes/
    getAttributeSetByProfilePath: /cm/metadata/attributes/, attrProfileId
    getExternalEntitiesPath: /cm/metadata/externalEntities/
    getEntityMetadataSetPath: /cm/metadata/externalEntities/, collectionId
    getEntityMetadataPath: /cm/metadata/externalEntities/, collectionId, entityId
    getAllMicroservicesPath: /cm/metadata/microservices/
    getMicroservicesByApiClassPath: /cm/metadata/microservices/, apiClass
    getInternalsPath: /cm/metadata/internal/
    getConfigurationPath: /cm/metadata/internal/, confId
    url: https://vm.project-seal.eu:9083
  sm:
    url: http://5.79.83.118:9090
  keystore:
    path: /etc/seal/testKeys/keystore.jks
    pass:
    key.pass:
    httpsig.cert.alias:
    httpsig.attempts:
    async.signature: true
    signing.secret:
  request:
    expire: 86400
    lloa: low
    # Validity of an issued link. 0 means permanent
    validityDays: 5
  resources:
    users:
      path: /etc/seal/resources/users-cm.json
      cache: 300000
    ms:
      path: /etc/seal/resources/microservices.json
      cache: 3600000
  auth.callback: http://localhost:8090/link/auth/callback
---
spring:
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql-service:3306/seal_linking?autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username:
    password:
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: create
    show-sql: true
server:
  port: 8090
linking:
  cm:
    getAttributeProfilesPath: /cm/metadata/attributes/
    getAttributeSetByProfilePath: /cm/metadata/attributes/, attrProfileId
    getExternalEntitiesPath: /cm/metadata/externalEntities/
    getEntityMetadataSetPath: /cm/metadata/externalEntities/, collectionId
    getEntityMetadataPath: /cm/metadata/externalEntities/, collectionId, entityId
    getAllMicroservicesPath: /cm/metadata/microservices/
    getMicroservicesByApiClassPath: /cm/metadata/microservices/, apiClass
    getInternalsPath: /cm/metadata/internal/
    getConfigurationPath: /cm/metadata/internal/, confId
    url: https://vm.project-seal.eu:9083
  sm:
    url: http://5.79.83.118:9090
  keystore:
    path: /app/data/testKeys/keystore.jks
    pass:
    key.pass:
    httpsig.cert.alias:
    httpsig.attempts:
    async.signature: true
    signing.secret:
  request:
    expire: 86400
    lloa: low
    # Validity of an issued link. 0 means permanent
    validityDays: 5
  resources:
    users:
      path: /app/data/resources/users-cm.json
      cache: 300000
    ms:
      path: /app/data/resources/microservices.json
      cache: 3600000
  auth.callback: http://localhost:8070/link/auth/callback
---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true


##
## SEAL configuration manager. To be read from environment variables (dockerization)
##
linking:
  cm:
    getAttributeProfilesPath: /cm/metadata/attributes/
    getAttributeSetByProfilePath: /cm/metadata/attributes/, attrProfileId
    getExternalEntitiesPath: /cm/metadata/externalEntities/
    getEntityMetadataSetPath: /cm/metadata/externalEntities/, collectionId
    getEntityMetadataPath: /cm/metadata/externalEntities/, collectionId, entityId
    getAllMicroservicesPath: /cm/metadata/microservices/
    getMicroservicesByApiClassPath: /cm/metadata/microservices/, apiClass
    getInternalsPath: /cm/metadata/internal/
    getConfigurationPath: /cm/metadata/internal/, confId
    url: https://vm.project-seal.eu:9083

  request:
    expire: 86400
    lloa: low
    # Validity of an issued link. 0 means permanent
    validityDays: 0
