spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seal_linking?autoReconnect=true&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: seal_linking
    password: 123clauer
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddlAuto: create
    show-sql: true

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialize: true


##
## SEAL configuration manager. To be read from environment variables (dockerization)
##
linking.cm:
  getAttributeProfilesPath: /cm/metadata/attributes/
  getAttributeSetByProfilePath: /cm/metadata/attributes/, attrProfileId
  getExternalEntitiesPath: /cm/metadata/externalEntities/
  getEntityMetadataSetPath: /cm/metadata/externalEntities/, collectionId
  getEntityMetadataPath: /cm/metadata/externalEntities/, collectionId, entityId
  getAllMicroservicesPath: /cm/metadata/microservices/
  getMicroservicesByApiClassPath: /cm/metadata/microservices/, apiClass
  getInternalsPath: /cm/metadata/internal/
  getConfigurationPath: /cm/metadata/internal/, confId